chateau.wad
de_storm.wad
halflife.wad
gfx/env/snowlake_up.tga
gfx/env/snowlake_dn.tga
gfx/env/snowlake_lf.tga
gfx/env/snowlake_rt.tga
gfx/env/snowlake_ft.tga
gfx/env/snowlake_bk.tga
sound/bio_survivor/ez_metel.wav
sound/bio_survivor/ez_zvuk1.wav
sound/bio_survivor/ez_vert.wav
sound/bio_survivor/ez_svuk2.wav
sound/ambience/waterleak_loop1.wav
models/bio_survivor/ez_car2b.mdl
models/bio_survivor/ez_lampa.mdl
sound/ambience/3dmbridge.wav
models/bio_survivor/ez_trup.mdl
sprites/glow02.spr
