zm_austria
gfx/env/xmas_streetsbk.tga
gfx/env/xmas_streetsdn.tga
gfx/env/xmas_streetsft.tga
gfx/env/xmas_streetslf.tga
gfx/env/xmas_streetsrt.tga
gfx/env/xmas_streetsup.tga
models/austria/austbochki.mdl
models/austria/lampbase.mdl
models/austria/lamplight.mdl
models/austria/shelves_wood.mdl
models/austria/snowbush.mdl
models/austria/tree3.mdl
models/austria/tree_snow.mdl
sound/zm_austria/cave2.wav
sound/zm_austria/caveambience.wav
sound/zm_austria/fire.wav
sound/zm_austria/midnightbell.wav
sound/zm_austria/safereturn.wav
sound/zm_austria/valve.wav
sound/zm_austria/wind.wav
sprites/glow01.spr
sprites/glow03.spr
sprites/zm_austria/flame2.spr
