de_piranesi.wad
halflife.wad
gfx/env/tornskybk.tga
gfx/env/tornskydn.tga
gfx/env/tornskyft.tga
gfx/env/tornskylf.tga
gfx/env/tornskyrt.tga
gfx/env/tornskyup.tga
models/bigtree.mdl
models/bush.mdl
models/pi_bush.mdl
models/pi_fern.mdl
models/pi_tree.mdl
models/pi_tree1.mdl
models/pi_tree2.mdl
models/pi_tree3.mdl
models/pi_twig.mdl
models/pred_plant.mdl
sound/storm/thunder-theme.wav
