de_piranesi.wad
halflife.wad
gfx/env/de_stormbk.tga
gfx/env/de_stormdn.tga
gfx/env/de_stormft.tga
gfx/env/de_stormlf.tga
gfx/env/de_stormrt.tga
gfx/env/de_stormup.tga
models/bigtree.mdl
models/boid.mdl
models/bskull_template1.mdl
models/fern.mdl
models/pi_fern.mdl
models/pi_tree.mdl
models/pi_tree2.mdl
models/pi_tree3.mdl
models/sot/ship_sail1.mdl
models/sot/ship_sail2.mdl
models/tree1.mdl
sound/ambience/3dmthrill.wav
sound/ambience/Birds9.wav
sound/ambience/kajika.wav
sound/ambience/rain.wav
sound/storm/thunder-theme.wav
