// zm_oldstreet3
//

gfx/env/zmcoastalup.tga
gfx/env/zmcoastaldn.tga
gfx/env/zmcoastallf.tga
gfx/env/zmcoastalrt.tga
gfx/env/zmcoastalft.tga
gfx/env/zmcoastalbk.tga
models/zm_oldstreet_cso/dnc_palm1.mdl
models/zm_oldstreet_cso/light.mdl
models/zm_oldstreet_cso/lamppost.mdl
models/zm_oldstreet_cso/fence_01.mdl
sound/zm_oldstreet_cso/outside_wind.wav
sprites/glow01.spr
models/can.mdl
sound/zm_oldstreet_cso/dist_shout_2.wav
models/zm_oldstreet_cso/billboard_02.mdl
models/zm_oldstreet_cso/sing_02.mdl
models/zm_oldstreet_cso/bus_stop.mdl
sound/zm_oldstreet_cso/siren.wav
models/zm_oldstreet_cso/newspaper_box.mdl
sound/zm_oldstreet_cso/chopper_1.wav
sound/zm_oldstreet_cso/dist_explosion.wav
models/zm_oldstreet_cso/sing_01.mdl
sound/zm_oldstreet_cso/dist_shout_1.wav
sound/zm_oldstreet_cso/carspin.wav
sound/zm_oldstreet_cso/music_01.wav
sound/zm_oldstreet_cso/music_02.wav
models/zm_oldstreet_cso/sing_03.mdl
