gfx/env/snowhiu_bk.tga
gfx/env/snowhiu_dn.tga
gfx/env/snowhiu_ft.tga
gfx/env/snowhiu_lf.tga
gfx/env/snowhiu_rt.tga
gfx/env/snowhiu_up.tga
models/snowhiu/model01.mdl
models/snowhiu/model02.mdl
models/snowhiu/model03.mdl
models/snowhiu/model04.mdl
models/snowhiu/model05.mdl
models/snowhiu/model06.mdl
models/snowhiu/model07.mdl
models/snowhiu/model08.mdl
sound/snowhiu/sound01.wav
sound/snowhiu/sound02.wav
sound/snowhiu/sound03.wav
sound/snowhiu/sound04.wav
sound/snowhiu/sound05.wav
sound/snowhiu/sound06.wav
sprites/glow01.spr
sprites/glow02.spr
