// zp_riversidebk
gfx/env/zp_riversidebk.tga
gfx/env/zp_riversidedn.tga
gfx/env/zp_riversideft.tga
gfx/env/zp_riversidelf.tga
gfx/env/zp_riversidert.tga
gfx/env/zp_riversideup.tga
models/dx/maps/3d_build_04.mdl
models/dx/maps/baby_crib.mdl
models/dx/maps/bed_01.mdl
models/dx/maps/billboard_01.mdl
models/dx/maps/bus_stop.mdl
models/dx/maps/bush_01.mdl
models/dx/maps/bush_05.mdl
models/dx/maps/car_01.mdl
models/dx/maps/car_04.mdl
models/dx/maps/hatch_road.mdl
models/dx/maps/lamppost.mdl
models/dx/maps/light_01.mdl
models/dx/maps/light_05.mdl
models/dx/maps/newspaper_box.mdl
models/dx/maps/sing_03.mdl
models/dx/maps/spotlight.mdl
models/dx/maps/tree_06.mdl
models/dx/maps/tree_09a.mdl
sound/dx/maps/carspin.wav
sound/dx/maps/crate_move.wav
sound/dx/maps/industrial.wav
sound/dx/maps/outside_wind.wav
sound/dx/maps/scream1.wav
sound/dx/maps/scream2.wav
sound/dx/maps/siren.wav
sound/dx/maps/underground.wav
sound/dx/maps/water_01.wav
sound/dx/mod/invis_start1.wav
sprites/dx/maps/game_enemy.spr
sprites/dx/maps/game_use.spr
sprites/dx/maps/light.spr
sprites/glow01.spr
