// zp_town

gfx/env/zmcoastalbk.tga
gfx/env/zmcoastaldn.tga
gfx/env/zmcoastalft.tga
gfx/env/zmcoastallf.tga
gfx/env/zmcoastalrt.tga
gfx/env/zmcoastalup.tga
models/zp_town/billboard_01.mdl
models/zp_town/billboard_03.mdl
models/zp_town/bus_stop.mdl
models/zp_town/car1.mdl
models/zp_town/car2.mdl
models/zp_town/car3.mdl
models/zp_town/car4.mdl
models/zp_town/clothing_pile_01.mdl
models/zp_town/couch_01.mdl
models/zp_town/dead_01.mdl
models/zp_town/fence_01.mdl
models/zp_town/lamppost.mdl
models/zp_town/light.mdl
models/zp_town/newspaper_box.mdl
models/zp_town/pipe_02.mdl
models/zp_town/shelves_wood.mdl
models/zp_town/signalbox.mdl
models/zp_town/sing_02.mdl
models/zp_town/sing_03.mdl
models/zp_town/table_01.mdl
models/zp_town/tree.mdl
models/zp_town/trees.mdl
sound/zp_town/dist_shout_1.wav
sound/zp_town/dist_shout_2.wav
sound/zp_town/generator.wav
sound/zp_town/music_1.wav
sound/zp_town/music_2.wav
sound/zp_town/outside_wind.wav
sound/zp_town/phone.wav
sound/zp_town/siren.wav
sprites/glow01.spr
